import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import yaml from 'js-yaml';
import SettingsForms from '@deepseek-ai/dsh-settings';
import ConfigEditor from '@deepseek-ai/dsh-config-editor';
import {Config} from '../lib/index.js';
import {liveConfig,loadComposition} from './helpers.js';

const inheritedSecret='fixture-inherited-private-key';
const profileSecret='fixture-profile-private-key';
const ns='hindsight-memory';
function descriptor(ctx,redactSecrets=true) {
  const row=ctx.get('settings').describe({redactSecrets}).find(row=>row.ns===ns);
  assert.ok(row,'native autogenerated settings must include the shipped hindsight-memory entry');
  return row;
}
function assertRedacted(row,...secrets) {
  for(const layer of ['value','base','user']) assert.equal(Object.hasOwn(row[layer],'apiKey'),false,`${layer} must omit the API secret`);
  for(const secret of secrets) assert.ok(!JSON.stringify(row).includes(secret),'no settings wire layer may expose a secret');
  assert.deepEqual(row.secrets,[{path:['apiKey'],set:true}]);
}

// All services, including ConfigEditor and SettingsForms, are imported from
// profile cordis patches by app-boot's real root Include, not mounted as fakes.
test('real profile Loader settings projects the complete Config and redacts resolved, inherited, and user API secrets',async t=>{
  const ctx=await loadComposition(t,{
    enabled:false,apiKey:profileSecret,bankId:'profile-bank',autoRetain:false,
  },{settings:true,inheritedConfig:{enabled:false,apiKey:inheritedSecret,bankId:'bundle-bank'}});
  const loader=ctx.get('loader');
  assert.equal(loader.resolve('include:settings').fiber.runtime.callback,SettingsForms);
  assert.equal(loader.resolve('include:config-editor').fiber.runtime.callback,ConfigEditor);
  const profile=ctx.get('profileContext');
  assert.equal(ctx.get('settings').documentPath,profile.patchPath);
  assert.equal(await ctx.get('settings').prepareDocument(),profile.patchPath);
  assert.ok(ctx.get('configEditor').entries().some(entry=>entry.options.id===ns));

  const row=descriptor(ctx);
  assert.equal(row.applies,'live');
  assert.equal(row.autoGenerate,true);
  const schema=row.schema.refs[row.schema.uid];
  const field=name=>row.schema.refs[schema.dict[name]];
  assert.equal(schema.type,'object');
  assert.deepEqual(Object.keys(schema.dict).sort(),Object.keys(Config.dict).sort(),'every tunable must be exposed by the real volatile form projection');
  for(const node of Object.values(row.schema.refs)) assert.equal(node.meta?.volatile,undefined,'wire schema contains plain values, not volatile references');
  assert.equal(field('apiKey').meta.role,'secret');
  assert.equal(Object.hasOwn(field('apiKey').meta,'default'),false,'secret defaults must not cross the wire');
  assert.equal(Object.hasOwn(field('apiKey').meta,'required'),false);
  assert.equal(field('bankId').type,'string');
  assert.equal(field('autoRetain').type,'boolean');
  assert.equal(field('recallMaxTokens').meta.min,64);
  assert.equal(row.value.bankId,'profile-bank');
  assert.equal(row.value.autoRetain,false);
  assert.equal(row.base.bankId,'bundle-bank');
  assert.equal(row.user.bankId,'profile-bank');
  assertRedacted(row,inheritedSecret,profileSecret);
  const local=descriptor(ctx,false);
  assert.equal(local.value.apiKey,profileSecret,'redaction is meaningful: the real loaded config contains the fixture secret');
  assert.equal(local.base.apiKey,inheritedSecret);
  assert.equal(local.user.apiKey,profileSecret);
});

test('real settings edits persist through ConfigEditor, update the same Loader fiber, and reject stale or invalid writes',async t=>{
  const ctx=await loadComposition(t,{
    enabled:false,apiKey:profileSecret,bankId:'before',autoRetain:true,
  },{settings:true});
  const settings=ctx.get('settings');
  const entry=ctx.get('loader').resolve('include:'+ns);
  const uid=entry.fiber.uid;
  const config=entry.fiber.config;
  const before=descriptor(ctx);
  await settings.mutate(ns,[
    {op:'set',path:['bankId'],value:'after'},
    {op:'set',path:['autoRetain'],value:false},
  ],before.revision);
  const after=descriptor(ctx);
  assert.ok(after.revision>before.revision);
  assert.equal(entry.fiber.uid,uid,'volatile edits must not remount the plugin');
  assert.equal(entry.fiber.config,config,'the existing volatile references must be updated');
  assert.equal(liveConfig(entry).bankId,'after');
  assert.equal(liveConfig(entry).autoRetain,false);
  assert.equal(liveConfig(entry).apiKey,profileSecret,'editing other fields must preserve write-only secrets');
  assertRedacted(after,profileSecret);
  const path=ctx.get('profileContext').patchPath;
  const persisted=await readFile(path,'utf8');
  const patch=yaml.load(persisted).find(row=>row.id===ns);
  assert.equal(patch.config.bankId,'after');
  assert.equal(patch.config.autoRetain,false);
  assert.equal(patch.config.apiKey,profileSecret);

  await assert.rejects(settings.update(ns,{bankId:'stale'},before.revision),{code:'SETTINGS_CONFLICT'});
  assert.equal(await readFile(path,'utf8'),persisted,'a stale edit must not write the profile patch');
  await assert.rejects(settings.update(ns,{recallMaxTokens:12},after.revision));
  assert.equal(await readFile(path,'utf8'),persisted,'schema validation must reject invalid config before persistence');
  assert.equal(liveConfig(entry).bankId,'after');
  assert.equal(liveConfig(entry).recallMaxTokens,1024);
  assert.equal(descriptor(ctx).revision,after.revision);
});

test('real settings distinguishes an explicit empty API key from resetting to the inherited key without exposing either secret',async t=>{
  const ctx=await loadComposition(t,{
    enabled:false,apiKey:profileSecret,apiKeyEnv:'',bankId:'profile-bank',
  },{settings:true,inheritedConfig:{enabled:false,apiKey:inheritedSecret,apiKeyEnv:'',bankId:'bundle-bank'}});
  const settings=ctx.get('settings');
  const entry=ctx.get('loader').resolve('include:'+ns);
  const uid=entry.fiber.uid;
  await settings.mutate(ns,[{op:'set',path:['apiKey'],value:''}],descriptor(ctx).revision);
  assert.equal(liveConfig(entry).apiKey,'','explicit empty means no API key');
  assertRedacted(descriptor(ctx),profileSecret,inheritedSecret);
  let patch=yaml.load(await readFile(ctx.get('profileContext').patchPath,'utf8')).find(row=>row.id===ns);
  assert.equal(patch.config.apiKey,'');
  await settings.mutate(ns,[{op:'unset',path:['apiKey']}],descriptor(ctx).revision);
  assert.equal(liveConfig(entry).apiKey,inheritedSecret,'unset resets to the inherited bundle key');
  assert.equal(liveConfig(entry).bankId,'profile-bank','resetting a secret preserves unrelated fields');
  assert.equal(entry.fiber.uid,uid);
  assertRedacted(descriptor(ctx),profileSecret,inheritedSecret);
  patch=yaml.load(await readFile(ctx.get('profileContext').patchPath,'utf8')).find(row=>row.id===ns);
  assert.equal(patch.config.apiKey,inheritedSecret);
});
